version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guest_service_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    networks:
      - guest_service_network
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: guest_service_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guest_service
    ports:
      - "3306:3306"
    networks:
      - guest_service_network

networks:
  guest_service_network:
    driver: bridge
